adminUser: admin

adminPassword: admin123

service:
  type: LoadBalancer

datasources:
  datasources.yaml:
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        isDefault: true

        url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090

persistence:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 300m

    memory: 512Mi
