apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-autoscaler

rules:

  - apiGroups: [""]
    resources:
      - events
      - endpoints
    verbs:
      - create
      - patch

  - apiGroups: [""]
    resources:
      - pods/eviction
    verbs:
      - create

  - apiGroups: [""]
    resources:
      - pods/status
    verbs:
      - update

  - apiGroups: [""]
    resources:
      - endpoints
    resourceNames:
      - cluster-autoscaler
    verbs:
      - get
      - update

  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - watch
      - list
      - get
      - update

  - apiGroups: [""]
    resources:
      - pods
      - services
      - replicationcontrollers
      - persistentvolumeclaims
      - persistentvolumes
    verbs:
      - watch
      - list
      - get

  - apiGroups: ["apps"]
    resources:
      - statefulsets
      - replicasets
      - daemonsets
    verbs:
      - watch
      - list
      - get

  - apiGroups: ["extensions"]
    resources:
      - replicasets
      - daemonsets
    verbs:
      - watch
      - list
      - get

  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs:
      - watch
      - list

  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
      - csinodes
    verbs:
      - watch
      - list
      - get

  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    verbs:
      - create
      - get
      - update
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-autoscaler

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-autoscaler

subjects:
  - kind: ServiceAccount
    name: cluster-autoscaler
    namespace: kube-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system

spec:
  replicas: 1

  selector:
    matchLabels:
      app: cluster-autoscaler

  template:
    metadata:
      labels:
        app: cluster-autoscaler

    spec:
      serviceAccountName: cluster-autoscaler

      containers:
        - name: cluster-autoscaler

          image: registry.k8s.io/autoscaling/cluster-autoscaler:v1.31.0

          imagePullPolicy: Always

          command:
            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=info
            - --cloud-provider=aws
            - --skip-nodes-with-local-storage=false
            - --expander=least-waste
            - --balance-similar-node-groups
            - --skip-nodes-with-system-pods=false
            - --scale-down-unneeded-time=2m
            - --scale-down-delay-after-add=2m
            - --scale-down-delay-after-delete=1m
            - --scale-down-delay-after-failure=1m
            - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/ultimate-eks-cluster

          resources:
            limits:
              cpu: 200m
              memory: 300Mi

            requests:
              cpu: 100m
              memory: 300Mi
