name: Terraform Infrastructure Pipeline

on:
push:
branches:
- main

pull_request:
branches:
- main

workflow_dispatch:

jobs:
terraform:
name: Terraform Validation
runs-on: ubuntu-latest


defaults:
  run:
    working-directory: terraform

steps:

  #################################################
  # CHECKOUT
  #################################################

  - name: Checkout Repository
    uses: actions/checkout@v4

  #################################################
  # TERRAFORM SETUP
  #################################################

  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v3

  #################################################
  # TERRAFORM FORMAT
  #################################################

  - name: Terraform Format Check
    run: terraform fmt -check -recursive

  #################################################
  # TERRAFORM INIT
  #################################################

  - name: Terraform Init
    run: terraform init

  #################################################
  # TERRAFORM VALIDATE
  #################################################

  - name: Terraform Validate
    run: terraform validate

  #################################################
  # TERRAFORM PLAN
  #################################################

  - name: Terraform Plan
    run: terraform plan -out=tfplan

  #################################################
  # UPLOAD PLAN ARTIFACT
  #################################################

  - name: Upload Terraform Plan
    uses: actions/upload-artifact@v4
    with:
      name: terraform-plan
      path: terraform/tfplan

  #################################################
  # SUCCESS MESSAGE
  #################################################

  - name: Terraform Pipeline Success
    run: |
      echo "===================================="
      echo "Terraform Validation Successful"
      echo "===================================="
